### ISSUE TITLE
Joint Optimization of Algorithmic Suites for EEG Analysis - questions

### ISSUE THREAD

**Issue by ghost** [EderSantana/DeepEEG#2]
<p style="text-align: justify;">Hello,
I am trying to get into detail of "<em>Joint Optimization of Algoritmic Suites for EEG Analysis</em>". I have several questions, the first one being a technical one: I am using the database '<em>sp1s_aa.mat</em>', it contains 316 labeled epoches. I split this database into two parts in ratio of 1/10 and use the larger part for training and (1/10) for the testing. I supply these to '<em>piecewise_deep_csp.py</em>'. I am running the code in Anaconda environment, Python 2.7.11 on Windows 7 - 64 bit with installed Theano and a GeForce GTX 750 Ti videocard. When running the module '<em>piecewise_deep_csp.py</em>' I am getting an error at the line:</p>

<hr />

<p style="text-align: justify;">train_model = theano.function([index], cost, updates=updates,
givens={
X: x_train_filt_T[index * batch_size: (index + 1) * batch_size],
y: y_train_T[index * batch_size: (index + 1) * batch_size]})</p>

<hr />

<p style="text-align: justify;">With <em>device = gpu</em> the error message is:</p>

<p style="text-align: justify;"><em>File "C:\Anaconda2\lib\site-packages\theano\tensor\type.py", line 218, in filter_variable</em>
<em> self=self)</em></p>

<p style="text-align: justify;"><em>TypeError: Cannot convert Type TensorType(float64, 3D) (of Variable Subtensor{int64:int64:}.0) into Type TensorType(float32, 3D). You can try to manually convert Subtensor{int64:int64:}.0 into a TensorType(float32, 3D).</em></p>

<hr />

<p style="text-align: justify;">With <em>device = cpu</em> the error message is:</p>

<p style="text-align: justify;"><em>File "C:\Anaconda2\lib\site-packages\theano\compile\pfunc.py", line 217, in rebuild_collect_shared</em>
<em> raise TypeError(err_msg, err_sug)</em></p>

<p style="text-align: justify;"><em>TypeError: ('An update must have the same type as the original shared variable (shared_var=W, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{sub,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')</em></p>

<hr />

<p style="text-align: justify;">I am confused where to search for the problem: am I missing something when preparing the input data set and supply it to the module, or it is a problem with my particular system, e.g. problems with not-properly installed libraries etc.
Any help would be appreciated.</p>

Kamen

**Comment by EderSantana** [comment]
it seems that you just have to downcast your data to float32. Something like:
`x_train_filt_T = x_train_filt_T.astype('float32')`

**Comment by dldl3D** [comment]
@EderSantana  I have the same question. I have downcasted my data to float32. But a new error is occurred.
'Traceback (most recent call last):
  File "piecewise_deep_csp.py", line 136, in <module>
    er = test_model()
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 618, in **call**
    storage_map=self.fn.storage_map)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 297, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 607, in **call**
    outputs = self.fn()
ValueError: Input dimension mis-match. (input[0].shape[0] = 32, input[1].shape[0] = 1)
Apply node that caused the error: Elemwise{Composite{NEQ(i0, Cast{int32}(i1))}}(argmax, <TensorType(int64, vector)>)
Toposort index: 41
Inputs types: [TensorType(int64, vector), TensorType(int64, vector)]
Inputs shapes: [(32,), (1,)]
Inputs strides: [(8,), (8,)]
Inputs values: ['not shown', array([1])]
Outputs clients: [[Sum{acc_dtype=int64}(Elemwise{Composite{NEQ(i0, Cast{int32}(i1))}}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
'
How can I solve these problem? Thank you.
