### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by HengNN** [EderSantana/DeepEEG#4]
Hello, can you send your dataset to me?
The dataset on http://www.bbci.de/competition/ii/ is different with yours, because I can't run your code successfully, there is no 'y_test' tag in .mat file.

**Comment by EderSantana** [comment]
Hi, this is an old project and I don't have the files anymore.
Please use this code as a reference for modern implementation.
I'd also recommend using pytorch or tensorflow now instead of theano as used here
